repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3.12

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8

-   repo: https://github.com/python-poetry/poetry
    rev: 1.3.0  
    hooks:
        - id: poetry-check
        - id: poetry-lock
        - id: poetry-export
          args: ["-f", "requirements.txt"]
